### ISSUE TITLE
It's not possible to download an AE file

### ISSUE THREAD

**Issue by yasman-opstalent** [think-jam/ReMake-Support#23]
### Current Behavior

AE file download is failling and returns an error in the browser.

![image](https://github.com/think-jam/ReMake-Support/assets/118522073/4545fd3c-60b4-4dc4-8e2a-9e089dc42685)

### Expected Behavior

AE file is downloaded without issues.

**Comment by yasman-opstalent** [comment]
Here is an example of a AE file:
https://app.remake.video/asset-library?p=62de41125f3a4f2d983d7b07/65d6111207d82300218400e8/65d62a8007d8230021844a13/65d62a8007d8230021844a17/

Environment: MT
Organization: Amazon

**Comment by tristan-remake** [comment]
that is a PSD not an AE file

**Comment by tristan-remake** [comment]
That ae file is from a deleted version of the original, which is a PSD

https://app.remake.video/remake/65d6111207d82300218400e4/static-original/65d8f7387621d20013402019/edit/65dcbc360c94020021677510

I attempted to make it as an After Effects project and render to Frame_png but I could not use that as a format because of the filename.

Why are you trying to download this project?

**Comment by yasman-opstalent** [comment]
@MikeCowler is this still happening for you?

**Comment by MikeCowler** [comment]
This is working. close ticket

**Comment by tristan-remake** [comment]
I was trying to create statics with After Effects. That is the project in the screenshot. I deleted the original because of the filenaming behaviour. We can look into using after effects for certain statics in the future but ignore for now. I do not know ho created the original ticket, but this file is of no use for any other testing
