### ISSUE TITLE
Live preview for Unilever project doesn't work

### ISSUE THREAD

**Issue by yasman-opstalent** [think-jam/ReMake-Support#44]
### Current Behavior

Render works, live preview doesn't work:
https://app.remake.video/original/61b22ba3274cac0033d0e6b4?sort=desc&sortBy=_id&assigned=false

### Expected Behavior

Render and live preview work.

**Comment by lazaroofarrill-opstalent** [comment]
The project has multiple compositions and items with the same name. `FIND OUT MORE BOX`. This is not supported by Remake.

**Comment by MikeCowler** [comment]
What is the solution? This used to be supported? If that is the case we have a lot of these old ae files there.

**Comment by lazaroofarrill-opstalent** [comment]
This project will not work because multiple compositions and layers share the same name. In order to avoid this issue. Projects should avoid to repeat the same name across several items.

**Comment by MikeCowler** [comment]
This has come about because we disabled the functionality to gang layers with the same name so they take the same image or text. This means we have a lot of Unilever material in the platform that now has this issue. I would like us to figure out some kind of workaround for this so we do not have to go in and re-ingest all this material.
